movieapp/urls.py
from django.urls import path, include
from . import views

app_name = "movieapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk_>", views.detail, name="detail"),
    path("delete/<int:pk_>", views.delete, name="delete"),
    path("update/<int:pk_>", views.update, name="update"),
    path("edit/<int:pk_>", views.edit, name="edit"),
    path("heart/<int:pk_>", views.heart, name="heart"),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movieapp.urls")),
]

movieapp/models.py
from statistics import mode
from turtle import title, update
from venv import create
from xmlrpc.client import DateTime
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hearted = models.BooleanField(default=False)

movieapp/views.py
from email import contentmanager
from django.shortcuts import render, redirect
from .models import Movie

# main page 이동 메소드
def index(reqeust):
    movies = Movie.objects.order_by("-hearted", "-created_at")
    context = {
        "movies": movies,
    }
    return render(reqeust, "review/index.html", context)


def new(reqeust):
    return render(reqeust, "review/new.html")


# detail.html로 이동 메소드
def detail(request, pk_):
    # 여기서 객체를 생성 => context
    target = Movie.objects.get(id=pk_)

    context = {"target": target}

    return render(request, "review/detail.html", context)


# 생성 메소드
def create(reqeust):
    obj = reqeust.GET
    Movie.objects.create(
        title=obj.get("title"),
        content=obj.get("content"),
        created_at=obj.get("created_at"),
        updated_at=obj.get("updated_at"),
    )
    return redirect("movieapp:index")


# 삭제 메소드
def delete(request, pk_):
    target = Movie.objects.get(id=pk_)
    target.delete()

    return redirect("movieapp:index")


# 업데이트 관련 메소드
def update(request, pk_):
    target = Movie.objects.get(id=pk_)
    # 내용 채울 예정
    target.title = request.POST.get("title")
    target.content = request.POST.get("content")
    target.save()
    return redirect("movieapp:index")


def edit(request, pk_):
    target = Movie.objects.get(id=pk_)
    context = {
        "target": target,
    }
    return render(request, "review/edit.html", context)


def heart(request, pk_):
    target = Movie.objects.get(id=pk_)

    if target.hearted:
        target.hearted = False
    else:
        target.hearted = True

    target.save()
    return redirect("movieapp:index")

movieapp/templates/review/detail.html
{% extends 'base.html' %}
{% block content %}
<!-- 게시글 상세 페이지 -->

<div class="d-flex justify-content-between mb-0">
  <div>
    <p class="fs-2 fw-bold">{{ target.title}}</p>
  </div>
  <div class="d-flex flex-column align-items-end">
    <p class="mb-0">작성일 | {{ target.created_at | date:'Y년 m월 d일 H:i'}}</p>
    <p class="mb-0">수정일 | {{ target.updated_at | date:'Y년 m월 d일 H:i'}}</p>
  </div>
</div>
<hr class="my-0">
<p class="ms-1 mt-4">{{ target.content}}</p>


<!-- 수정 / 삭제 버튼 -->
<div class="text-end mt-5">
  <a href=" {% url 'movieapp:index' %}">
    <button type="button" class="btn btn-outline-primary me-2">목록으로</button>
  </a>
  <a href=" {% url 'movieapp:edit' target.pk %}">
    <button type="button" class="btn btn-outline-success me-2">수정</button>
  </a>
  <a href="{% url 'movieapp:delete' target.pk %}">
    <button type="button" class="btn btn-outline-danger">삭제</button>
  </a>
</div>
{% endblock %}

movieapp/templates/review/edit.html
{% extends 'base.html'%}
{% block style %}
<style>
    textarea {
        width: 100%;
        height: 300px;
        resize: none;
        border-color: rgb(190, 184, 184);
        border-radius: 10px 10px 10px 10px;
        padding: 10px;
    }
</style>
{% endblock %}
{% block content %}
<h1 class="text-center mb-5">수정하기</h1>
<form action="{% url 'movieapp:update' target.pk %}" method="post">
    {% csrf_token %}
    <div class="form-floating mb-3">
        <input name="title" value="{{ target.title }}" type=" text" class="form-control" id="floatingInput"
            placeholder="name@example.com">
        <label for="floatingInput"></label>
    </div>
    <textarea name="content" class="mb-5">{{ target.content }}</textarea>
    <div>
        <input type="submit" class="btn btn-primary w-100" value="수정"></input>
    </div>
</form>



{% endblock %}

movieapp/templates/review/index.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <h1 class="mt-5 text-center">DC아웃사이드 영화갤러리</h1>
    <div class="w-100 my-5">
        <a href="{% url 'movieapp:new' %}">
            <button type="button" class="btn btn-outline-primary w-100">글 작성</button>
        </a>
    </div>
    <div class="main-board">
        {% for movie in movies %}

        <div class="shadow p-3 mb-1 bg-body rounded">
            <div class="d-flex">
                <div class="w-100">
                    <a href="{% url 'movieapp:detail' movie.pk %}">
                        <p>{{ movie.title}}</p>
                        <p>{{movie.created_at|date:'Y-m-d' }}</p>
                    </a>
                </div>
                <p class="hearting">
                    {% if movie.hearted == True %}
                    <a href="{% url 'movieapp:heart' movie.pk%}">
                        <i style="color: red" class="fa-solid fa-heart"></i>
                    </a>
                    {% else %}
                    <a href="{% url 'movieapp:heart' movie.pk%}">
                        <i class="fa-regular fa-heart"></i>
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

movieapp/templates/review/new.html
{% extends 'base.html'%}
{% block style %}
<style>
    textarea {
        width: 100%;
        height: 300px;
        resize: none;
        border-color: rgb(190, 184, 184);
        border-radius: 10px 10px 10px 10px;
        padding: 10px;
    }
</style>
{% endblock %}
{% block content %}
<h1 class="text-center mb-5">작성하기</h1>
<form action="{% url 'movieapp:create' %}">
    <div class="form-floating mb-5">
        <input name="title" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
        <label for="floatingInput">글 제목</label>
    </div>
    <textarea id="textarea" name="content" class="mb-5"></textarea>
    <div>
        <input type="submit" class="btn btn-primary w-100"></input>
    </div>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        @font-face {
            font-family: 'GangwonEdu_OTFBoldA';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        a {
            text-decoration: none;
            color: black
        }

        .hearting {
            margin-top: 20px;
            font-size: 35px;

        }

        * {
            font-family: 'GangwonEdu_OTFBoldA';
        }

        p {
            font-size: 20px;
        }
    </style>
    {% block style %}
    {% endblock %}
</head>

<body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
            <title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
                d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z">
            </path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
            <path
                d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path
                d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
            <path
                d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
        </symbol>
    </svg>
    <div class="container mt-5">
        <div class="shadow-lg p-3 mb-5 bg-body rounded">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- JavaScript Bundle with Popper -->
    {% block script %}
    {% endblock %}
    <footer class="container">
        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
            <p>© 2022-09-30 이용택 이상백 PAIR PROJECT</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                            <use xlink:href="#twitter"></use>
                        </svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                            <use xlink:href="#instagram"></use>
                        </svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                            <use xlink:href="#facebook"></use>
                        </svg></a></li>
            </ul>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>